//  AppLink.h
//  SyncProxy
//  Copyright (c) 2014 Ford Motor Company. All rights reserved.

//Proxy
#import <AppLink/SDLJingle.h>
#import <AppLink/SDLProxyListener.h>
#import <AppLink/SDLRPCRequestFactory.h>
#import <AppLink/SDLProxy.h>
#import <AppLink/SDLProxyFactory.h>
#import <AppLink/SDLTTSChunkFactory.h>

//Debug
#import <AppLink/SDLConsoleController.h>
#import <AppLink/SDLDebugTool.h>
#import <AppLink/SDLSiphonServer.h>

//RPC Requests
#import <AppLink/SDLAddCommand.h>
#import <AppLink/SDLAddSubMenu.h>
#import <AppLink/SDLAlert.h>
#import <AppLink/SDLAlertManeuver.h>
#import <AppLink/SDLChangeRegistration.h>
#import <AppLink/SDLCreateInteractionChoiceSet.h>
#import <AppLink/SDLDeleteCommand.h>
#import <AppLink/SDLDeleteFile.h>
#import <AppLink/SDLDeleteInteractionChoiceSet.h>
#import <AppLink/SDLDeleteSubMenu.h>
#import <AppLink/SDLDiagnosticMessage.h>
#import <AppLink/SDLEncodedSyncPData.h>
#import <AppLink/SDLEndAudioPassThru.h>
#import <AppLink/SDLGetDTCs.h>
#import <AppLink/SDLGetVehicleData.h>
#import <AppLink/SDLListFiles.h>
#import <AppLink/SDLPerformAudioPassThru.h>
#import <AppLink/SDLPerformInteraction.h>
#import <AppLink/SDLPutFile.h>
#import <AppLink/SDLReadDID.h>
#import <AppLink/SDLRegisterAppInterface.h>
#import <AppLink/SDLResetGlobalProperties.h>
#import <AppLink/SDLScrollableMessage.h>
#import <AppLink/SDLSetAppIcon.h>
#import <AppLink/SDLSetDisplayLayout.h>
#import <AppLink/SDLSetGlobalProperties.h>
#import <AppLink/SDLSetMediaClockTimer.h>
#import <AppLink/SDLShow.h>
#import <AppLink/SDLShowConstantTBT.h>
#import <AppLink/SDLSlider.h>
#import <AppLink/SDLSpeak.h>
#import <AppLink/SDLSubscribeButton.h>
#import <AppLink/SDLSubscribeVehicleData.h>
#import <AppLink/SDLSyncPData.h>
#import <AppLink/SDLUpdateTurnList.h>
#import <AppLink/SDLUnregisterAppInterface.h>
#import <AppLink/SDLUnsubscribeButton.h>
#import <AppLink/SDLUnsubscribeVehicleData.h>

//RPC Responses
#import <AppLink/SDLAddCommandResponse.h>
#import <AppLink/SDLAddSubMenuResponse.h>
#import <AppLink/SDLAlertResponse.h>
#import <AppLink/SDLAlertManeuverResponse.h>
#import <AppLink/SDLChangeRegistrationResponse.h>
#import <AppLink/SDLCreateInteractionChoiceSetResponse.h>
#import <AppLink/SDLDeleteCommandResponse.h>
#import <AppLink/SDLDeleteFileResponse.h>
#import <AppLink/SDLDeleteInteractionChoiceSetResponse.h>
#import <AppLink/SDLDeleteSubMenuResponse.h>
#import <AppLink/SDLDiagnosticMessageResponse.h>
#import <AppLink/SDLEncodedSyncPDataResponse.h>
#import <AppLink/SDLEndAudioPassThruResponse.h>
#import <AppLink/SDLGenericResponse.h>
#import <AppLink/SDLGetDTCsResponse.h>
#import <AppLink/SDLGetVehicleDataResponse.h>
#import <AppLink/SDLListFilesResponse.h>
#import <AppLink/SDLPerformAudioPassThruResponse.h>
#import <AppLink/SDLPerformInteractionResponse.h>
#import <AppLink/SDLPutFileResponse.h>
#import <AppLink/SDLReadDIDResponse.h>
#import <AppLink/SDLRegisterAppInterfaceResponse.h>
#import <AppLink/SDLResetGlobalPropertiesResponse.h>
#import <AppLink/SDLScrollableMessageResponse.h>
#import <AppLink/SDLSetAppIconResponse.h>
#import <AppLink/SDLSetDisplayLayoutResponse.h>
#import <AppLink/SDLSetGlobalPropertiesResponse.h>
#import <AppLink/SDLSetMediaClockTimerResponse.h>
#import <AppLink/SDLShowConstantTBTResponse.h>
#import <AppLink/SDLShowResponse.h>
#import <AppLink/SDLSliderResponse.h>
#import <AppLink/SDLSpeakResponse.h>
#import <AppLink/SDLSubscribeButtonResponse.h>
#import <AppLink/SDLSubscribeVehicleDataResponse.h>
#import <AppLink/SDLSyncPDataResponse.h>
#import <AppLink/SDLUpdateTurnListResponse.h>
#import <AppLink/SDLUnregisterAppInterfaceResponse.h>
#import <AppLink/SDLUnsubscribeButtonResponse.h>
#import <AppLink/SDLUnsubscribeVehicleDataResponse.h>

//RPC Notifications
#import <AppLink/SDLOnAppInterfaceUnregistered.h>
#import <AppLink/SDLOnAudioPassThru.h>
#import <AppLink/SDLOnButtonEvent.h>
#import <AppLink/SDLOnButtonPress.h>
#import <AppLink/SDLOnCommand.h>
#import <AppLink/SDLOnDriverDistraction.h>
#import <AppLink/SDLOnEncodedSyncPData.h>
#import <AppLink/SDLOnHashChange.h>
#import <AppLink/SDLOnHMIStatus.h>
#import <AppLink/SDLOnKeyboardInput.h>
#import <AppLink/SDLOnLanguageChange.h>
#import <AppLink/SDLOnLockScreenStatus.h>
#import <AppLink/SDLOnPermissionsChange.h>
#import <AppLink/SDLOnSyncPData.h>
#import <AppLink/SDLOnSystemRequest.h>
#import <AppLink/SDLOnVehicleData.h>
#import <AppLink/SDLOnTBTClientState.h>
#import <AppLink/SDLOnTouchEvent.h>
#import <AppLink/SDLOnVehicleData.h>

//RPC Structs
#import <AppLink/SDLAirbagStatus.h>
#import <AppLink/SDLAudioPassThruCapabilities.h>
#import <AppLink/SDLBeltStatus.h>
#import <AppLink/SDLBodyInformation.h>
#import <AppLink/SDLButtonCapabilities.h>
#import <AppLink/SDLChoice.h>
#import <AppLink/SDLClusterModeStatus.h>
#import <AppLink/SDLDeviceInfo.h>
#import <AppLink/SDLDeviceStatus.h>
#import <AppLink/SDLDIDResult.h>
#import <AppLink/SDLDisplayCapabilities.h>
#import <AppLink/SDLECallInfo.h>
#import <AppLink/SDLEmergencyEvent.h>
#import <AppLink/SDLGPSData.h>
#import <AppLink/SDLHeadLampStatus.h>
#import <AppLink/SDLHMIPermissions.h>
#import <AppLink/SDLImage.h>
#import <AppLink/SDLKeyboardProperties.h>
#import <AppLink/SDLMenuParams.h>
#import <AppLink/SDLMyKey.h>
#import <AppLink/SDLParameterPermissions.h>
#import <AppLink/SDLPermissionItem.h>
#import <AppLink/SDLPresetBankCapabilities.h>
#import <AppLink/SDLSingleTireStatus.h>
#import <AppLink/SDLSoftButton.h>
#import <AppLink/SDLSoftButtonCapabilities.h>
#import <AppLink/SDLStartTime.h>
#import <AppLink/SDLSyncMsgVersion.h>
#import <AppLink/SDLTextField.h>
#import <AppLink/SDLTireStatus.h>
#import <AppLink/SDLTTSChunk.h>
#import <AppLink/SDLTurn.h>
#import <AppLink/SDLVehicleDataResult.h>
#import <AppLink/SDLVehicleType.h>
#import <AppLink/SDLVrHelpItem.h>

//RPC Enums
#import <AppLink/SDLAppHMIType.h>
#import <AppLink/SDLAppInterfaceUnregisteredReason.h>
#import <AppLink/SDLAudioStreamingState.h>
#import <AppLink/SDLAudioType.h>
#import <AppLink/SDLBitsPerSample.h>
#import <AppLink/SDLButtonEventMode.h>
#import <AppLink/SDLButtonName.h>
#import <AppLink/SDLButtonPressMode.h>
#import <AppLink/SDLCarModeStatus.h>
#import <AppLink/SDLECallConfirmationStatus.h>
#import <AppLink/SDLCharacterSet.h>
#import <AppLink/SDLCompassDirection.h>
#import <AppLink/SDLComponentVolumeStatus.h>
#import <AppLink/SDLDimension.h>
#import <AppLink/SDLDisplayType.h>
#import <AppLink/SDLDriverDistractionState.h>
#import <AppLink/SDLDeviceLevelStatus.h>
#import <AppLink/SDLEmergencyEventType.h>
#import <AppLink/SDLFileType.h>
#import <AppLink/SDLFuelCutoffStatus.h>
#import <AppLink/SDLGlobalProperty.h>
#import <AppLink/SDLHMILevel.h>
#import <AppLink/SDLHmiZoneCapabilities.h>
#import <AppLink/SDLIgnitionStableStatus.h>
#import <AppLink/SDLIgnitionStatus.h>
#import <AppLink/SDLImageType.h>
#import <AppLink/SDLInteractionMode.h>
#import <AppLink/SDLKeyboardEvent.h>
#import <AppLink/SDLKeyboardLayout.h>
#import <AppLink/SDLKeypressMode.h>
#import <AppLink/SDLLanguage.h>
#import <AppLink/SDLLockScreenStatus.h>
#import <AppLink/SDLMaintenanceModeStatus.h>
#import <AppLink/SDLMediaClockFormat.h>
#import <AppLink/SDLPermissionStatus.h>
#import <AppLink/SDLPowerModeQualificationStatus.h>
#import <AppLink/SDLPowerModeStatus.h>
#import <AppLink/SDLPrimaryAudioSource.h>
#import <AppLink/SDLPRNDL.h>
#import <AppLink/SDLResult.h>
#import <AppLink/SDLRPCMessageType.h>
#import <AppLink/SDLSamplingRate.h>
#import <AppLink/SDLScreenParams.h>
#import <AppLink/SDLSoftButtonType.h>
#import <AppLink/SDLSpeechCapabilities.h>
#import <AppLink/SDLSystemAction.h>
#import <AppLink/SDLSystemContext.h>
#import <AppLink/SDLTBTState.h>
#import <AppLink/SDLTextAlignment.h>
#import <AppLink/SDLTextFieldName.h>
#import <AppLink/SDLTimerMode.h>
#import <AppLink/SDLTriggerSource.h>
#import <AppLink/SDLUpdateMode.h>
#import <AppLink/SDLVehicleDataActiveStatus.h>
#import <AppLink/SDLVehicleDataEventStatus.h>
#import <AppLink/SDLVehicleDataNotificationStatus.h>
#import <AppLink/SDLVehicleDataResultCode.h>
#import <AppLink/SDLVehicleDataStatus.h>
#import <AppLink/SDLVehicleDataType.h>
#import <AppLink/SDLVrCapabilities.h>
#import <AppLink/SDLWarningLightStatus.h>
#import <AppLink/SDLWiperStatus.h>