//
//  SDLAudioData.h
//  SmartDeviceLink
//
//  Created by Nicole on 11/9/20.
//  Copyright © 2020 smartdevicelink. All rights reserved.
//

#import <Foundation/Foundation.h>

#import "SDLSpeechCapabilities.h"

@class SDLFile;
@class SDLTTSChunk;

NS_ASSUME_NONNULL_BEGIN

@interface SDLAudioData : NSObject

/// The underlying prompt generated by the `init`.
@property (nullable, copy, nonatomic, readonly) NSArray<SDLTTSChunk *> *prompt;

/// If created with an audio file, the audio file that will be uploaded and used.
@property (nullable, copy, nonatomic, readonly) SDLFile *audioFile;

/// Initialize with an SDLFile holding data or pointing to a file on the file system. When this object is passed to an `Alert` or `Speak`, the file will be uploaded if it is not already, then played if the system supports that feature.
/// @discussion Only available on systems supporting RPC Spec v.5.0+
///
/// @param audioFile The audio file to be played by the system
- (instancetype)initWithAudioFile:(SDLFile *)audioFile;

/// Initialize with a string to be spoken by the system speech synthesizer.
/// @param spokenString The string to be spoken by the system speech synthesizer
- (instancetype)initWithSpeechSynthesizerString:(NSString *)spokenString;

/// Initialize with a string to be spoken by the system speech synthesizer using a phonetic string.
/// @param phoneticString The string to be spoken by the system speech synthesizer
/// @param phoneticType Must be one of `SAPI_PHONEMES`, `LHPLUS_PHONEMES`, `TEXT`, or `PRE_RECORDED` or no object will be created
- (instancetype)initWithPhoneticSpeechSynthesizerString:(NSString *)phoneticString phoneticType:(SDLSpeechCapabilities)phoneticType;

- (instancetype)init NS_UNAVAILABLE; 

@end

NS_ASSUME_NONNULL_END
