//  SDLPowerModeQualificationStatus.h
//


#import "SDLEnum.h"

typedef SDLEnum SDLPowerModeQualificationStatus NS_EXTENSIBLE_STRING_ENUM;

extern SDLPowerModeQualificationStatus const SDLPowerModeQualificationStatusPowerModeUndefined;
extern SDLPowerModeQualificationStatus const SDLPowerModeQualificationStatusPowerModeEvaluationInProgress;
extern SDLPowerModeQualificationStatus const SDLPowerModeQualificationStatusNotDefined;
extern SDLPowerModeQualificationStatus const SDLPowerModeQualificationStatusPowerModeOk;
