//  SDLPredefinedLayout.h
//


#import "SDLEnum.h"

typedef SDLEnum SDLPredefinedLayout NS_EXTENSIBLE_STRING_ENUM;

extern SDLPredefinedLayout const SDLPredefinedLayoutDefault;
extern SDLPredefinedLayout const SDLPredefinedLayoutMedia;
extern SDLPredefinedLayout const SDLPredefinedLayoutNonMedia;
extern SDLPredefinedLayout const SDLPredefinedLayoutOnscreenPresets;
extern SDLPredefinedLayout const SDLPredefinedLayoutNavFullscreenMap;
extern SDLPredefinedLayout const SDLPredefinedLayoutNavList;
extern SDLPredefinedLayout const SDLPredefinedLayoutNavKeyboard;
extern SDLPredefinedLayout const SDLPredefinedLayoutGraphicWithText;
extern SDLPredefinedLayout const SDLPredefinedLayoutTextWithGraphic;
extern SDLPredefinedLayout const SDLPredefinedLayoutTilesOnly;
extern SDLPredefinedLayout const SDLPredefinedLayoutTextButtonsOnly;
extern SDLPredefinedLayout const SDLPredefinedLayoutGraphicWithTiles;
extern SDLPredefinedLayout const SDLPredefinedLayoutTilesWithGraphic;
extern SDLPredefinedLayout const SDLPredefinedLayoutGraphicWithTextAndSoftButtons;
extern SDLPredefinedLayout const SDLPredefinedLayoutTextAndSoftButtonsWithGraphic;
extern SDLPredefinedLayout const SDLPredefinedLayoutGraphicWithTextButtons;
extern SDLPredefinedLayout const SDLPredefinedLayoutTextButtonsWithGraphic;
extern SDLPredefinedLayout const SDLPredefinedLayoutLargeGraphicWithSoftButtons;
extern SDLPredefinedLayout const SDLPredefinedLayoutDoubleGraphicWithSoftButtons;
extern SDLPredefinedLayout const SDLPredefinedLayoutLargeGraphicOnly;
