//  SDLPredefinedLayout.h
//


#import "SDLEnum.h"

typedef SDLEnum SDLPredefinedLayout SDL_SWIFT_ENUM;

extern SDLPredefinedLayout const SDLPredefinedLayoutDefault;
extern SDLPredefinedLayout const SDLPredefinedLayoutMedia;
extern SDLPredefinedLayout const SDLPredefinedLayoutNonMedia;
extern SDLPredefinedLayout const SDLPredefinedLayoutOnscreenPresets;
extern SDLPredefinedLayout const SDLPredefinedLayoutNavigationFullscreenMap;
extern SDLPredefinedLayout const SDLPredefinedLayoutNavigationList;
extern SDLPredefinedLayout const SDLPredefinedLayoutNavigationKeyboard;
extern SDLPredefinedLayout const SDLPredefinedLayoutGraphicWithText;
extern SDLPredefinedLayout const SDLPredefinedLayoutTextWithGraphic;
extern SDLPredefinedLayout const SDLPredefinedLayoutTilesOnly;
extern SDLPredefinedLayout const SDLPredefinedLayoutTextButtonsOnly;
extern SDLPredefinedLayout const SDLPredefinedLayoutGraphicWithTiles;
extern SDLPredefinedLayout const SDLPredefinedLayoutTilesWithGraphic;
extern SDLPredefinedLayout const SDLPredefinedLayoutGraphicWithTextAndSoftButtons;
extern SDLPredefinedLayout const SDLPredefinedLayoutTextAndSoftButtonsWithGraphic;
extern SDLPredefinedLayout const SDLPredefinedLayoutGraphicWithTextButtons;
extern SDLPredefinedLayout const SDLPredefinedLayoutTextButtonsWithGraphic;
extern SDLPredefinedLayout const SDLPredefinedLayoutLargeGraphicWithSoftButtons;
extern SDLPredefinedLayout const SDLPredefinedLayoutDoubleGraphicWithSoftButtons;
extern SDLPredefinedLayout const SDLPredefinedLayoutLargeGraphicOnly;
