//  SDLPowerModeQualificationStatus.h
//


#import "SDLEnum.h"

typedef SDLEnum SDLPowerModeQualificationStatus NS_STRING_ENUM;

extern SDLPowerModeQualificationStatus const SDLPowerModeQualificationStatusUndefined;
extern SDLPowerModeQualificationStatus const SDLPowerModeQualificationStatusEvaluationInProgress;
extern SDLPowerModeQualificationStatus const SDLPowerModeQualificationStatusNotDefined;
extern SDLPowerModeQualificationStatus const SDLPowerModeQualificationStatusOk;
