//  SDLPRNDL.m
//


#import "SDLPRNDL.h"

SDLPRNDL const SDLPRNDLPark = @"PARK";
SDLPRNDL const SDLPRNDLReverse = @"REVERSE";
SDLPRNDL const SDLPRNDLNeutral = @"NEUTRAL";
SDLPRNDL const SDLPRNDLDrive = @"DRIVE";
SDLPRNDL const SDLPRNDLSport = @"SPORT";
SDLPRNDL const SDLPRNDLLowGear = @"LOWGEAR";
SDLPRNDL const SDLPRNDLFirst = @"FIRST";
SDLPRNDL const SDLPRNDLNinth = @"NINTH";
SDLPRNDL const SDLPRNDLSecond = @"SECOND";
SDLPRNDL const SDLPRNDLTenth = @"TENTH";
SDLPRNDL const SDLPRNDLThird = @"THIRD";
SDLPRNDL const SDLPRNDLFourth = @"FOURTH";
SDLPRNDL const SDLPRNDLFifth = @"FIFTH";
SDLPRNDL const SDLPRNDLSixth = @"SIXTH";
SDLPRNDL const SDLPRNDLSeventh = @"SEVENTH";
SDLPRNDL const SDLPRNDLEighth = @"EIGHTH";
SDLPRNDL const SDLPRNDLUnknown = @"UNKNOWN";
SDLPRNDL const SDLPRNDLFault = @"FAULT";
