//  SDLResetGlobalProperties.h
//
//  Copyright (c) 2014 Ford Motor Company. All rights reserved.

#import <Foundation/Foundation.h>
#import <SmartDeviceLink/SDLRPCRequest.h>

/**
 * Resets the passed global properties to their default values as defined by
 * SYNC
 * <p>
 * The HELPPROMPT global property default value is generated by SYNC consists of
 * the first vrCommand of each Command Menu item defined at the moment PTT is
 * pressed<br/>
 * The TIMEOUTPROMPT global property default value is the same as the HELPPROMPT
 * global property default value
 * <p>
 * <b>HMILevel needs to be FULL, LIMITED or BACKGROUND</b>
 * </p>
 *
 * Since AppLink 1.0
 * See SetGlobalProperties
 */
@interface SDLResetGlobalProperties : SDLRPCRequest {}

/**
 * @abstract Constructs a new SDLResetGlobalProperties object
 */
-(id) init;
/**
 * @abstract Constructs a new SDLResetGlobalProperties object indicated by the NSMutableDictionary
 * parameter
 * @param dict The NSMutableDictionary to use
 */
-(id) initWithDictionary:(NSMutableDictionary*) dict;

/**
 * @abstract An array of one or more GlobalProperty enumeration elements
 * indicating which global properties to reset to their default value
 */
@property(strong) NSMutableArray* properties;

@end
